### PR TITLE
Extensions

### PR DESCRIPTION
**Pull request by caseyparker**
Added the [decentraleyes](https://github.com/Synzvato/decentraleyes) extension
Updated privacybadger, uBlock, and https-everywhere to the current versions
updated the README.md to link to each extension included.
Pull if you'd like.

### CODE REVIEW

**Comment by caseyparker** [comment]
Is there any objection to including decentraleyes? Please advise so this can go forward or diverge here.

**Comment by zgrimshell** [comment]
Hi (to chip in but I haven't actually reviewed it)

0. the code looks to be young thus potentially unstable (you really don't want to just add another add-on to remove it a month later)

1. has anyone audited the code (security-wise but also general wise to avoid hardly maintainable code) as adding a new code is adding to bigger attack surface too.

2. AFAIK our OS is going to be Debian based, so maybe making it as separate package (maybe you are doing it already, I didn't look into details) and adding it into Depends (or Recommends as they are installed by default in Debian) for PureBrowser would be much more elegant choice. If this sounds good I also suggest maintaining the same package in Debian to avoid deltas as afterall maintaining browser is already horror stories by itself :)

**Comment by caseyparker** [comment]
Valid points. Up through now, the included extensions are actually just kind of added in, in order to make them non-removable. So far yes, maintaining the browser has been a bit of its own little horror story, definitely agree there.

**Comment by pospeselr** [comment]
Perhaps a bit off topic, but why does Purism maintain its own browser?

**Comment by caseyparker** [comment]
@pospeselr That would probably be a question for @toddatpurism ... I do use the browser though, it's nicer than trying to cobble together the same thing from a firefox install.

**Pull request merged**
